#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2013 Gaudenz Steinlin <gaudenz@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

Remove_persistent_cdrom ()
{
	if [ -e /etc/udev/rules.d/70-persistent-cd.rules ]
	then
		echo -n " remove-persistent-cdrom"

		rm /etc/udev/rules.d/70-persistent-cd.rules
	fi
}

Remove_persistent_cdrom
