#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.

KEYBOARD_STATE_FILE="/var/lib/live/lernstick-config/kde-keyboard-fixup"
KXKBRC="/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc"

Kde_keyboard ()
{
	echo -n " kde-keyboard-configuration"

	# Checking if KDE is installed
	[ -e /usr/share/kde4 ] || return 0

	[ "${KEYBOARD_CHANGED}" = "true" ] || return 0

	Configure_kde_keyboard
}

Configure_kde_keyboard ()
{
	# update layouts in keyboard selector
	dir="$(dirname $KXKBRC)"
	[ -d "${dir}" ] || mkdir -p "${dir}"

	if [ ! -e "${KXKBRC}" ]
	then
cat > "${KXKBRC}" << EOF
[Layout]
DisplayNames=${LIVE_KEYBOARD_LAYOUTS}
IndicatorOnly=false
LayoutList=${LIVE_KEYBOARD_LAYOUTS}
Model=${LIVE_KEYBOARD_MODEL}
ShowFlag=true
SwitchMode=Global
Use=true
EOF
	else
		sed --in-place --expression="s/DisplayNames=.*/DisplayNames=${LIVE_KEYBOARD_LAYOUTS}/" \
		    --expression="s/LayoutList=.*/LayoutList=${LIVE_KEYBOARD_LAYOUTS}/" \
		    --expression="s/Model=.*/Model=${LIVE_KEYBOARD_MODEL}/" \
		    "${KXKBRC}"
	fi

	chown ${LIVE_USERNAME}:${LIVE_USERNAME} "${KXKBRC}"
	rm -f "/home/${LIVE_USERNAME}/.kde/share/apps/kded/session/keyboard/layout_memory.xml"
	# should enable kxkb in ~/.kde/share/config/kxkbrc
	# if multiple layouts are specified. gnome does it per default.
}

Kde_keyboard
