#!/bin/sh

## live-config(7) - System Configuration Scripts
## Copyright (C) 2006-2013 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


Kde_services ()
{
	echo -n " kde-services"

	# Checking if package is installed
	if [ ! -e /usr/share/kde4 ]
	then
		return
	fi

	# Reading kernel command line
	for _PARAMETER in ${_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.keyboard-layouts=*|keyboard-layouts=*)
				LIVE_KEYBOARD_LAYOUTS="${_PARAMETER#*keyboard-layouts=}"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done

	# enforce "lazy change" (only run the remaining script if the keyboard setting was really changed)
	KEYBOARD_STATE_FILE="/var/lib/live/lernstick-config/kde-keyboard-fixup"
	if [ ! -r ${KEYBOARD_STATE_FILE} ] || [ "${LIVE_KEYBOARD_LAYOUTS}" != "$(cat ${KEYBOARD_STATE_FILE})" ]
	then
		echo "${LIVE_KEYBOARD_LAYOUTS}" > $KEYBOARD_STATE_FILE
		Configure_kde_services
	fi
}

Configure_kde_services ()
{
	# update layouts in keyboard selector
	mkdir -p "/home/${LIVE_USERNAME}/.kde/share/config/"

cat > "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" << EOF
[Layout]
DisplayNames=${LIVE_KEYBOARD_LAYOUTS}
IndicatorOnly=false
LayoutList=${LIVE_KEYBOARD_LAYOUTS}
ShowFlag=true
SwitchMode=Global
Use=true
EOF

	chown ${LIVE_USERNAME}:${LIVE_USERNAME} "/home/${LIVE_USERNAME}/.kde/share/config/kxkbrc" 
	rm -f "/home/${LIVE_USERNAME}/.kde/share/apps/kded/session/keyboard/layout_memory.xml"
	# should enable kxkb in ~/.kde/share/config/kxkbrc
	# if multiple layouts are specified. gnome does it per default.
}

Kde_services
